# Generated by Django 5.2 on 2025-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Architect Name', max_length=100)),
                ('headline', models.CharField(default='Architect & Interior Designer', max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_summary', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Enter skills separated by commas', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
