# Generated by Django 5.2 on 2025-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_goalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(default='#1b1f2a', help_text='Background color', max_length=7)),
                ('color_bg_alt', models.CharField(default='#2a2f3a', help_text='Alternative background (cards, modals)', max_length=7)),
                ('color_text', models.CharField(default='#e0d8c3', help_text='Main text color', max_length=7)),
                ('color_accent', models.CharField(default='#9d77c3', help_text='Accent color (buttons, links)', max_length=7)),
                ('color_accent_hover', models.CharField(default='#b39ddb', help_text='Hover version of accent color', max_length=7)),
                ('glow_color', models.CharField(default='#d8b4fe', help_text='Glow/hover effects', max_length=7)),
            ],
        ),
    ]
